In [47]:
import pandas as pd

In [48]:
raw = pd.read_csv('usretechnicalpotential.csv')

In [49]:
raw.head()

,Unnamed: 0,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,...,biopowerGaseous_GWh,biopowerGaseous_GW,biopowerGaseous_Tonnes-CH4,geothermalHydrothermal_GWh,geothermalHydrothermal_GW,EGSGeothermal_GWh,EGSGeothermal_GW,hydropower_GWh,hydropower_GW,hydropower_countOfSites
0,Alabama,35850,20,426,3706838,2114,44058,15475.0,12,0,...,1533,0,326186,0,0,535489.0,67.0,4102,0,2435
1,Alaska,166,0,2,8282976,9005,187608,NaN,1,0,...,61,0,13156,15437,1,NaN,NaN,23675,5,3053
2,Arizona,121305,52,1096,11867693,5147,107230,22736.0,14,12544333,...,837,0,178188,8329,1,1239147.0,157.0,1303,0,1958
3,Arkansas,28960,15,332,4986388,2747,57239,8484.0,6,0,...,1063,0,226178,0,0,628621.0,79.0,6093,1,3268
4,California,246008,111,2320,8855917,4010,83549,106411.0,75,8490916,...,15510,1,3300211,130921,16,1344179.0,170.0,30023,6,9692

In [50]:
raw.columns

Index(['Unnamed: 0', 'urbanUtilityScalePV_GWh', 'urbanUtilityScalePV_GW',
       'urbanUtilityScalePV_km2', 'ruralUtilityScalePV_GWh',
       'ruralUtilityScalePV_GW', 'ruralUtilityScalePV_km2', 'rooftopPV_GWh',
       'rooftopPV_GW', 'CSP_GWh', 'CSP_GW', 'CSP_km2', 'onshoreWind_GWh',
       'onshoreWind_GW', 'onshoreWind_km2', 'offshoreWind_GWh',
       'offshoreWind_GW', 'offshoreWind_km2', 'biopowerSolid_GWh',
       'biopowerSolid_GW', 'biopowerSolid_BDT', 'biopowerGaseous_GWh',
       'biopowerGaseous_GW', 'biopowerGaseous_Tonnes-CH4',
       'geothermalHydrothermal_GWh', 'geothermalHydrothermal_GW',
       'EGSGeothermal_GWh', 'EGSGeothermal_GW', 'hydropower_GWh',
       'hydropower_GW', 'hydropower_countOfSites'],
      dtype='object')

In [51]:
raw = raw.rename(columns={'Unnamed: 0': 'Region'})
raw

,Region,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,...,biopowerGaseous_GWh,biopowerGaseous_GW,biopowerGaseous_Tonnes-CH4,geothermalHydrothermal_GWh,geothermalHydrothermal_GW,EGSGeothermal_GWh,EGSGeothermal_GW,hydropower_GWh,hydropower_GW,hydropower_countOfSites
0,Alabama,35850,20,426,3706838,2114,44058,15475.0,12,0,...,1533,0,326186,0,0,535489.0,67.0,4102,0,2435
1,Alaska,166,0,2,8282976,9005,187608,NaN,1,0,...,61,0,13156,15437,1,NaN,NaN,23675,5,3053
2,Arizona,121305,52,1096,11867693,5147,107230,22736.0,14,12544333,...,837,0,178188,8329,1,1239147.0,157.0,1303,0,1958
3,Arkansas,28960,15,332,4986388,2747,57239,8484.0,6,0,...,1063,0,226178,0,0,628621.0,79.0,6093,1,3268
4,California,246008,111,2320,8855917,4010,83549,106411.0,75,8490916,...,15510,1,3300211,130921,16,1344179.0,170.0,30023,6,9692
5,Colorado,43470,19,399,10238083,4514,94046,16162.0,11,9154524,...,1224,0,260470,8953,1,1251657.0,158.0,7789,1,5060
6,Connecticut,7716,4,100,19627,12,256,6616.0,5,0,...,414,0,88227,0,0,56078.0,7.0,922,0,659
7,Delaware,14856,9,189,272332,167,3482,2185.0,1,0,...,385,0,82013,0,0,22813.0,2.0,30,0,25
8,District of Columbia,8,0,0,0,0,0,2490.0,2,0,...,4,0,977,0,0,697.0,0.0,0,0,2
9,Florida,72787,39,830,5137346,2812,58596,63986.0,49,358,...,3693,0,785787,0,0,374161.0,47.0,682,0,493
10,Georgia,43166,24,505,5492183,3088,64343,31116.0,24,0,...,2220,0,472546,0,0,353206.0,44.0,1988,0,2100
11,Hawaii,3725,1,34,38032,20,430,NaN,2,15369,...,200,0,42602,20632,2,NaN,NaN,2602,0,437
12,Idaho,23194,12,251,3936847,2045,42612,4051.0,3,3502877,...,182,0,38830,17205,2,993257.0,125.0,18757,4,6706
13,Illinois,103551,63,1324,8090985,4969,103524,30086.0,26,0,...,4222,0,898345,0,0,676055.0,85.0,4882,1,1330
14,Indiana,98815,61,1274,4876185,3018,62890,17151.0,14,0,...,2978,0,633660,0,0,434258.0,55.0,2394,0,1142
15,Iowa,27091,15,324,6994159,4020,83762,8646.0,7,0,...,1425,0,303277,0,0,606390.0,76.0,2818,0,2398
16,Kansas,31705,15,317,14500149,6959,144995,8962.0,6,7974255,...,753,0,160219,0,0,989675.0,125.0,2507,0,3201
17,Kentucky,26514,16,338,1823976,1119,23319,12312.0,10,0,...,1273,0,271052,0,0,484658.0,61.0,4255,0,1394
18,Louisiana,55669,32,674,4114605,2394,49876,14368.0,11,0,...,857,0,182404,0,0,484271.0,61.0,2423,0,934
19,Maine,3216,1,40,1100327,658,13722,2443.0,2,0,...,124,0,26542,0,0,377075.0,47.0,3916,0,1373
20,Maryland,28551,18,378,585949,373,7772,14849.0,12,0,...,1226,0,260965,0,0,86649.0,10.0,814,0,491
21,Massachusetts,17469,10,228,82204,51,1074,11722.0,10,0,...,1103,0,234811,0,0,92227.0,11.0,1196,0,560
22,Michigan,50845,33,699,5215639,3443,71740,23527.0,21,0,...,2539,0,540282,0,0,457850.0,58.0,1180,0,1942
23,Minnesota,33370,20,419,10792814,6510,135627,14321.0,12,0,...,1029,0,219074,0,0,369784.0,46.0,1254,0,1391
24,Mississippi,26366,15,317,4981252,2879,59996,8614.0,6,0,...,1076,0,229076,0,0,559056.0,70.0,2211,0,1536
25,Missouri,30549,18,376,5335268,3156,65766,16159.0,13,0,...,2147,0,456990,0,0,835444.0,105.0,7198,1,5089
26,Montana,11370,6,127,8187341,4402,91724,2194.0,1,1540287,...,147,0,31324,6547,0,1647303.0,208.0,14546,3,6859
27,Nebraska,12954,6,141,9266756,4869,101456,5336.0,4,4846929,...,750,0,159729,0,0,927996.0,117.0,3142,0,2880
28,Nevada,24893,10,224,8614454,3732,77751,10767.0,7,8295752,...,325,0,69248,45320,5,1262174.0,160.0,845,0,1489
29,New Hampshire,3790,2,48,57363,35,741,2298.0,2,0,...,389,0,82889,0,0,104314.0,13.0,1740,0,810
30,New Jersey,44307,25,527,439773,251,5231,15767.0,13,0,...,2310,0,491691,0,0,35230.0,4.0,549,0,402
31,New Mexico,71356,30,645,16318543,7087,147652,6513.0,4,16812349,...,353,0,75228,12933,1,1417978.0,179.0,1362,0,1810
32,New York,52803,32,682,1492566,926,19294,28779.0,25,0,...,2950,0,627734,0,0,375400.0,47.0,6711,1,4839
33,North Carolina,68346,37,789,4232789,2346,48892,28419.0,23,0,...,3780,0,804301,0,0,420741.0,53.0,3036,0,2131
34,North Dakota,4871,2,57,9734447,5482,114227,1916.0,1,36049,...,30,0,6383,0,0,820226.0,104.0,347,0,572
35,Ohio,86495,57,1190,3626181,2395,49908,30064.0,27,0,...,3363,0,715603,0,0,495921.0,62.0,3045,0,1791
36,Oklahoma,50040,25,533,9341920,4782,99640,12442.0,9,5068036,...,965,0,205359,0,0,779667.0,98.0,3015,0,2824
37,Oregon,25783,12,270,3740478,1884,39266,8322.0,7,2812126,...,890,0,189571,18199,2,914105.0,115.0,18184,4,7993
38,Pennsylvania,56161,36,754,553356,356,7429,22215.0,19,0,...,7132,0,1517540,0,0,327340.0,41.0,8368,1,4466
39,Rhode Island,1787,1,24,13636,8,184,1710.0,1,0,...,474,0,100888,0,0,11491.0,1.0,59,0,86
40,South Carolina,33834,19,397,2754973,1555,32398,14412.0,11,0,...,1430,0,304312,0,0,364104.0,46.0,1888,0,889
41,South Dakota,4573,2,50,10008873,5344,111350,2082.0,1,1629659,...,235,0,50072,0,0,921972.0,116.0,1047,0,1712
42,Tennessee,50243,28,595,2225989,1266,26395,19685.0,16,0,...,1984,0,422220,0,0,428380.0,54.0,5744,1,2610
43,Texas,294684,154,3213,38993581,20411,425230,78716.0,60,22786749,...,5898,0,1254999,0,0,3030250.0,384.0,3006,0,4366
44,Utah,30492,14,292,5184878,2390,49797,7513.0,5,5067546,...,427,0,91018,12981,1,939380.0,119.0,3528,0,3394
45,Vermont,1632,1,22,54727,35,739,1115.0,1,0,...,203,0,43248,0,0,35616.0,4.0,1710,0,1207
46,Virginia,27451,15,326,1882467,1074,22377,22266.0,18,0,...,2498,0,531592,0,0,290736.0,36.0,3656,0,2601
47,Washington,33690,19,402,1738150,996,20758,13599.0,13,161713,...,1514,0,322155,2546,0,563023.0,71.0,27248,6,7310
48,West Virginia,3023,2,41,52693,35,729,4220.0,3,0,...,281,0,59811,0,0,261376.0,33.0,4408,1,1711
49,Wisconsin,54938,34,727,5042258,3205,66788,13939.0,12,0,...,2072,0,441053,0,0,647173.0,82.0,2286,1,1863
50,Wyoming,7232,3,75,5727224,2854,59463,1550.0,1,5406407,...,50,0,10670,1373,0,1070078.0,135.0,4445,1,2842

In [52]:
types = ['PV', 'Wind', 'CSP', 'biopower', 'Hydrothermal', 'Geothermal', 'hydropower']
for t in types:
    related_cols = [c for c in raw.columns if ((t in c) & c.endswith('GW') & ('rooftop' not in c))]
    print(related_cols)
    raw['{}'.format(t.lower())] = raw[related_cols].sum(axis=1)

['urbanUtilityScalePV_GW', 'ruralUtilityScalePV_GW']
['onshoreWind_GW', 'offshoreWind_GW']
['CSP_GW']
['biopowerSolid_GW', 'biopowerGaseous_GW']
['geothermalHydrothermal_GW']
['EGSGeothermal_GW']
['hydropower_GW']

In [53]:
raw.head()

,Region,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,...,hydropower_GWh,hydropower_GW,hydropower_countOfSites,pv,wind,csp,biopower,hydrothermal,geothermal,hydropower
0,Alabama,35850,20,426,3706838,2114,44058,15475.0,12,0,...,4102,0,2435,2134,0.0,0,1,0,67.0,0
1,Alaska,166,0,2,8282976,9005,187608,NaN,1,0,...,23675,5,3053,9005,493.0,0,0,1,0.0,5
2,Arizona,121305,52,1096,11867693,5147,107230,22736.0,14,12544333,...,1303,0,1958,5199,10.0,3527,0,1,157.0,0
3,Arkansas,28960,15,332,4986388,2747,57239,8484.0,6,0,...,6093,1,3268,2762,9.0,0,1,0,79.0,1
4,California,246008,111,2320,8855917,4010,83549,106411.0,75,8490916,...,30023,6,9692,4121,688.0,2725,2,16,170.0,6

In [54]:
agg_natl = raw.sum()
agg_natl['Region'] = 'National'
agg_natl

Region                          National
urbanUtilityScalePV_GWh          2231670
urbanUtilityScalePV_GW              1195
urbanUtilityScalePV_km2            25343
ruralUtilityScalePV_GWh        280613190
ruralUtilityScalePV_GW            152950
ruralUtilityScalePV_km2          3186931
rooftopPV_GWh                   818711.0
rooftopPV_GW                         639
CSP_GWh                        116146234
CSP_GW                             38057
CSP_km2                          1157199
onshoreWind_GWh                 32783975
onshoreWind_GW                     10937
onshoreWind_km2                  2190929
offshoreWind_GWh              16975788.0
offshoreWind_GW                   4210.0
offshoreWind_km2                844688.0
biopowerSolid_GWh                 399750
biopowerSolid_GW                      30
biopowerSolid_BDT              363430992
biopowerGaseous_GWh                88528
biopowerGaseous_GW                     1
biopowerGaseous_Tonnes-CH4      18840706
geothermalHydrothermal_GWh        301376
geothermalHydrothermal_GW             32
EGSGeothermal_GWh             31344671.0
EGSGeothermal_GW                  3948.0
hydropower_GWh                    258929
hydropower_GW                         38
hydropower_countOfSites           128126
pv                                154145
wind                             15147.0
csp                                38057
biopower                              31
hydrothermal                          32
geothermal                        3948.0
hydropower                            38
dtype: object

In [55]:
raw.loc[len(raw.index)] = agg_natl
raw

,Region,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,...,hydropower_GWh,hydropower_GW,hydropower_countOfSites,pv,wind,csp,biopower,hydrothermal,geothermal,hydropower
0,Alabama,35850,20,426,3706838,2114,44058,15475.0,12,0,...,4102,0,2435,2134,0.0,0,1,0,67.0,0
1,Alaska,166,0,2,8282976,9005,187608,NaN,1,0,...,23675,5,3053,9005,493.0,0,0,1,0.0,5
2,Arizona,121305,52,1096,11867693,5147,107230,22736.0,14,12544333,...,1303,0,1958,5199,10.0,3527,0,1,157.0,0
3,Arkansas,28960,15,332,4986388,2747,57239,8484.0,6,0,...,6093,1,3268,2762,9.0,0,1,0,79.0,1
4,California,246008,111,2320,8855917,4010,83549,106411.0,75,8490916,...,30023,6,9692,4121,688.0,2725,2,16,170.0,6
5,Colorado,43470,19,399,10238083,4514,94046,16162.0,11,9154524,...,7789,1,5060,4533,387.0,3097,0,1,158.0,1
6,Connecticut,7716,4,100,19627,12,256,6616.0,5,0,...,922,0,659,16,7.0,0,0,0,7.0,0
7,Delaware,14856,9,189,272332,167,3482,2185.0,1,0,...,30,0,25,176,15.0,0,0,0,2.0,0
8,District of Columbia,8,0,0,0,0,0,2490.0,2,0,...,0,0,2,0,0.0,0,0,0,0.0,0
9,Florida,72787,39,830,5137346,2812,58596,63986.0,49,358,...,682,0,493,2851,9.0,0,1,0,47.0,0
10,Georgia,43166,24,505,5492183,3088,64343,31116.0,24,0,...,1988,0,2100,3112,58.0,0,1,0,44.0,0
11,Hawaii,3725,1,34,38032,20,430,NaN,2,15369,...,2602,0,437,21,738.0,5,0,2,0.0,0
12,Idaho,23194,12,251,3936847,2045,42612,4051.0,3,3502877,...,18757,4,6706,2057,18.0,1267,0,2,125.0,4
13,Illinois,103551,63,1324,8090985,4969,103524,30086.0,26,0,...,4882,1,1330,5032,264.0,0,3,0,85.0,1
14,Indiana,98815,61,1274,4876185,3018,62890,17151.0,14,0,...,2394,0,1142,3079,148.0,0,1,0,55.0,0
15,Iowa,27091,15,324,6994159,4020,83762,8646.0,7,0,...,2818,0,2398,4035,570.0,0,3,0,76.0,0
16,Kansas,31705,15,317,14500149,6959,144995,8962.0,6,7974255,...,2507,0,3201,6974,952.0,2884,1,0,125.0,0
17,Kentucky,26514,16,338,1823976,1119,23319,12312.0,10,0,...,4255,0,1394,1135,0.0,0,0,0,61.0,0
18,Louisiana,55669,32,674,4114605,2394,49876,14368.0,11,0,...,2423,0,934,2426,340.0,0,1,0,61.0,0
19,Maine,3216,1,40,1100327,658,13722,2443.0,2,0,...,3916,0,1373,659,158.0,0,0,0,47.0,0
20,Maryland,28551,18,378,585949,373,7772,14849.0,12,0,...,814,0,491,391,52.0,0,0,0,10.0,0
21,Massachusetts,17469,10,228,82204,51,1074,11722.0,10,0,...,1196,0,560,61,185.0,0,0,0,11.0,0
22,Michigan,50845,33,699,5215639,3443,71740,23527.0,21,0,...,1180,0,1942,3476,481.0,0,1,0,58.0,0
23,Minnesota,33370,20,419,10792814,6510,135627,14321.0,12,0,...,1254,0,1391,6530,518.0,0,2,0,46.0,0
24,Mississippi,26366,15,317,4981252,2879,59996,8614.0,6,0,...,2211,0,1536,2894,3.0,0,1,0,70.0,0
25,Missouri,30549,18,376,5335268,3156,65766,16159.0,13,0,...,7198,1,5089,3174,274.0,0,1,0,105.0,1
26,Montana,11370,6,127,8187341,4402,91724,2194.0,1,1540287,...,14546,3,6859,4408,944.0,557,0,0,208.0,3
27,Nebraska,12954,6,141,9266756,4869,101456,5336.0,4,4846929,...,3142,0,2880,4875,917.0,1753,2,0,117.0,0
28,Nevada,24893,10,224,8614454,3732,77751,10767.0,7,8295752,...,845,0,1489,3742,7.0,2557,0,5,160.0,0
29,New Hampshire,3790,2,48,57363,35,741,2298.0,2,0,...,1740,0,810,37,5.0,0,0,0,13.0,0
30,New Jersey,44307,25,527,439773,251,5231,15767.0,13,0,...,549,0,402,276,101.0,0,0,0,4.0,0
31,New Mexico,71356,30,645,16318543,7087,147652,6513.0,4,16812349,...,1362,0,1810,7117,492.0,4860,0,1,179.0,0
32,New York,52803,32,682,1492566,926,19294,28779.0,25,0,...,6711,1,4839,958,171.0,0,0,0,47.0,1
33,North Carolina,68346,37,789,4232789,2346,48892,28419.0,23,0,...,3036,0,2131,2383,306.0,0,1,0,53.0,0
34,North Dakota,4871,2,57,9734447,5482,114227,1916.0,1,36049,...,347,0,572,5484,770.0,13,1,0,104.0,0
35,Ohio,86495,57,1190,3626181,2395,49908,30064.0,27,0,...,3045,0,1791,2452,95.0,0,1,0,62.0,0
36,Oklahoma,50040,25,533,9341920,4782,99640,12442.0,9,5068036,...,3015,0,2824,4807,516.0,1812,0,0,98.0,0
37,Oregon,25783,12,270,3740478,1884,39266,8322.0,7,2812126,...,18184,4,7993,1896,252.0,1017,1,2,115.0,4
38,Pennsylvania,56161,36,754,553356,356,7429,22215.0,19,0,...,8368,1,4466,392,8.0,0,0,0,41.0,1
39,Rhode Island,1787,1,24,13636,8,184,1710.0,1,0,...,59,0,86,9,20.0,0,0,0,1.0,0
40,South Carolina,33834,19,397,2754973,1555,32398,14412.0,11,0,...,1888,0,889,1574,133.0,0,0,0,46.0,0
41,South Dakota,4573,2,50,10008873,5344,111350,2082.0,1,1629659,...,1047,0,1712,5346,882.0,589,1,0,116.0,0
42,Tennessee,50243,28,595,2225989,1266,26395,19685.0,16,0,...,5744,1,2610,1294,0.0,0,0,0,54.0,1
43,Texas,294684,154,3213,38993581,20411,425230,78716.0,60,22786749,...,3006,0,4366,20565,2172.0,7743,2,0,384.0,0
44,Utah,30492,14,292,5184878,2390,49797,7513.0,5,5067546,...,3528,0,3394,2404,13.0,1638,0,1,119.0,0
45,Vermont,1632,1,22,54727,35,739,1115.0,1,0,...,1710,0,1207,36,2.0,0,0,0,4.0,0
46,Virginia,27451,15,326,1882467,1074,22377,22266.0,18,0,...,3656,0,2601,1089,90.0,0,0,0,36.0,0
47,Washington,33690,19,402,1738150,996,20758,13599.0,13,161713,...,27248,6,7310,1015,138.0,58,1,0,71.0,6
48,West Virginia,3023,2,41,52693,35,729,4220.0,3,0,...,4408,1,1711,37,1.0,0,0,0,33.0,1
49,Wisconsin,54938,34,727,5042258,3205,66788,13939.0,12,0,...,2286,1,1863,3239,183.0,0,1,0,82.0,1
50,Wyoming,7232,3,75,5727224,2854,59463,1550.0,1,5406407,...,4445,1,2842,2857,552.0,1955,0,0,135.0,1
51,National,2231670,1195,25343,280613190,152950,3186931,818711.0,639,116146234,...,258929,38,128126,154145,15147.0,38057,31,32,3948.0,38

In [56]:
raw.to_csv('usretechnicalpotential_column_aggs.csv')

In [57]:
raw.loc[raw.Region== "National", [c for c in raw.columns if c.startswith("all")]].to_csv('usretechnicalpotential_national_column_aggs.csv')

# Power plant data

In [58]:
import os

In [59]:
df = pd.DataFrame()
for f in os.listdir(r"/Users/sarahscheurich/Downloads"):
    if f.endswith("Power_Plants.csv"):
        print(f)
        df = pd.concat([df, pd.read_csv(os.path.join("/Users/sarahscheurich/Downloads",f))])

Biomass_Power_Plants.csv
BatteryStorage_Power_Plants.csv
Solar_Power_Plants.csv
Pumped_Sotrage_Power_Plants.csv
Nuclear_Power_Plants.csv
Hydroelectric_Power_Plants.csv
Other_Power_Plants.csv
Natural_gas_Power_Plants.csv
Geothermal_Power_Plants.csv
Wind_Power_Plants.csv
Petroleum_Power_Plants.csv
Coal_Power_Plants.csv

In [60]:
df.head

<bound method NDFrame.head of               X          Y  OBJECTID                             Utility_Name  \
0   -118.111059  48.620336         1                              Avista Corp
1    -73.208056  44.491700         2       City of Burlington Electric - (VT)
2    -88.455800  46.755300         3       L'Anse Warden Electric Company LLC
3    -92.151711  46.735331         4                             ALLETE, Inc.
4    -92.516912  44.569200         5     Northern States Power Co - Minnesota
..          ...        ...       ...                                      ...
248  -89.215000  37.711944       249  Southern Illinois University Carbondale
249 -103.634380  41.858870       250                Western Sugar Cooperative
250  -83.447222  43.741111       251                   Michigan Sugar Company
251  -66.149897  17.947115       252                       AES Puerto Rico LP
252 -108.499232  45.765346       253    Western Sugar Cooperative  - Billings

     Utility_ID         Sector_Name          City        County      Zip  \
0         20169    Electric Utility  Kettle Falls       Stevens  99141.0
1          2548    Electric Utility    Burlington    Chittenden   5401.0
2         56133         IPP Non-CHP        L'Anse        Baraga  49946.0
3         12647      Commercial CHP        Duluth      St Louis  55807.0
4         13781    Electric Utility      Red Wing       Goodhue  55901.0
..          ...                 ...           ...           ...      ...
248       57306      Commercial CHP    Carbondale       Jackson  62901.0
249       57315  Industrial Non-CHP   Scottsbluff  Scotts Bluff  69361.0
250       57324      Industrial CHP     Sebewaing         Huron  48759.0
251       60697         IPP Non-CHP       Guayama       Guayama    785.0
252       61819      Industrial CHP      Billings   Yellowstone  59101.0

               Street_Address  ...    StateName  Plant_Code  \
0            1151 Hyw. 395 N.  ...   Washington         550
1          111 Intervale Road  ...      Vermont         589
2               157 S Main St  ...     Michigan        1772
3            4913 Main Street  ...    Minnesota        1897
4            801 5th st. East  ...    Minnesota        1926
..                        ...  ...          ...         ...
248  210 Physical Plant Drive  ...     Illinois       57928
249  2100 East Overland Drive  ...     Nebraska       57937
250                  947 Pine  ...     Michigan       57949
251     Carretera #3 Km 144.7  ...  Puerto Rico       61082
252         3020 State Avenue  ...      Montana       62319

                               Plant_Name  \
0         Kettle Falls Generating Station
1                              J C McNeil
2                           John H Warden
3                             M L Hibbard
4                                Red Wing
..                                    ...
248                                  SIUC
249      Western Sugar Coop - Scottsbluff
250                         MSC Sebewaing
251                       AES Puerto Rico
252  Western Sugar Cooperative - Billings

                                             tech_desc  \
0    Wood/Wood Waste Biomass; Natural Gas Fired Com...
1                              Wood/Wood Waste Biomass
2                              Wood/Wood Waste Biomass
3                              Wood/Wood Waste Biomass
4                                Municipal Solid Waste
..                                                 ...
248        Conventional Steam Coal; Petroleum Liquids;
249                            Conventional Steam Coal
250                            Conventional Steam Coal
251                            Conventional Steam Coal
252                            Conventional Steam Coal

                            Source  Geo_MW  Other_MW  Bio_MW  Bat_MW  \
0    EIA-860, EIA-860M and EIA-923     NaN       NaN    50.0     NaN
1    EIA-860, EIA-860M and EIA-923     NaN       NaN    52.0     NaN
2    EIA-860, EIA-860M and EIA-923     NaN       NaN    17.7     NaN
3    EIA-860, EIA-860M and EIA-923     NaN       NaN    60.0     NaN
4    EIA-860, EIA-860M and EIA-923     NaN       NaN    18.0     NaN
..                             ...     ...       ...     ...     ...
248  EIA-860, EIA-860M and EIA-923     NaN       NaN     NaN     NaN
249  EIA-860, EIA-860M and EIA-923     NaN       NaN     NaN     NaN
250  EIA-860, EIA-860M and EIA-923     NaN       NaN     NaN     NaN
251  EIA-860, EIA-860M and EIA-923     NaN       NaN     NaN     NaN
252  EIA-860, EIA-860M and EIA-923     NaN       NaN     NaN     NaN

     Data_Source
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
..           ...
248          NaN
249          NaN
250          NaN
251          NaN
252          NaN

[10847 rows x 35 columns]>

In [61]:
MW_cols = [c for c in df.columns if c.endswith("MW")]
MW_cols

['Install_MW',
 'Total_MW',
 'Coal_MW',
 'NG_MW',
 'Crude_MW',
 'Hydro_MW',
 'HydroPS_MW',
 'Nuclear_MW',
 'Solar_MW',
 'Wind_MW',
 'Geo_MW',
 'Other_MW',
 'Bio_MW',
 'Bat_MW']

In [62]:
df.shape

(10847, 35)

In [63]:
len(df.Utility_Name.unique()), len(df.Utility_ID.unique()),len(df.Plant_Code.unique()), len(df.Street_Address.unique())

(4997, 5015, 10847, 10149)

In [64]:
df.groupby('Utility_ID').count()

,X,Y,OBJECTID,Utility_Name,Sector_Name,City,County,Zip,Street_Address,PrimSource,...,StateName,Plant_Code,Plant_Name,tech_desc,Source,Geo_MW,Other_MW,Bio_MW,Bat_MW,Data_Source
Utility_ID,,,,,,,,,,,,,,,,,,,,,
7,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
8,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
25,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
34,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
35,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64344,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
64353,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
64367,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0
64378,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,0,0,0,0,0
64383,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,0,0,0,0

In [65]:
df.loc[df.Utility_ID == 64378]

,X,Y,OBJECTID,Utility_Name,Utility_ID,Sector_Name,City,County,Zip,Street_Address,...,StateName,Plant_Code,Plant_Name,tech_desc,Source,Geo_MW,Other_MW,Bio_MW,Bat_MW,Data_Source
4179,-80.253073,40.481959,4180,IMG Energy Solutions,64378,IPP Non-CHP,Findlay Township,Allegheny,15216.0,Harper Road,...,Pennsylvania,64874,PG Solar 1,Solar Photovoltaic,"EIA-860, EIA-860M and EIA-923",NaN,NaN,NaN,NaN,NaN
1431,-80.233000,40.495000,1432,IMG Energy Solutions,64378,IPP Non-CHP,Coraopolis,Allegheny,15108.0,485 Tower Road,...,Pennsylvania,64873,Pittsburgh Airport Gas Plant,Natural Gas Internal Combustion Engine,"EIA-860, EIA-860M and EIA-923",NaN,NaN,NaN,NaN,NaN

In [66]:
df.to_csv('Power_Plants_agg.csv')

In [67]:
df.columns

Index(['X', 'Y', 'OBJECTID', 'Utility_Name', 'Utility_ID', 'Sector_Name',
       'City', 'County', 'Zip', 'Street_Address', 'PrimSource', 'Install_MW',
       'Total_MW', 'Coal_MW', 'NG_MW', 'Crude_MW', 'Hydro_MW', 'HydroPS_MW',
       'Nuclear_MW', 'Solar_MW', 'Wind_MW', 'Source_Desc', 'Period',
       'Latitude', 'Longitude', 'StateName', 'Plant_Code', 'Plant_Name',
       'tech_desc', 'Source', 'Geo_MW', 'Other_MW', 'Bio_MW', 'Bat_MW',
       'Data_Source'],
      dtype='object')

In [76]:
sumdiv = lambda x: sum(x)
grpby_funcs = dict([(c, sum) for c in df.columns if c.endswith('MW')])

In [77]:
state_agg = df.groupby('StateName').agg(grpby_funcs)
state_agg.head()

,Install_MW,Total_MW,Coal_MW,NG_MW,Crude_MW,Hydro_MW,HydroPS_MW,Nuclear_MW,Solar_MW,Wind_MW,Geo_MW,Other_MW,Bio_MW,Bat_MW
StateName,,,,,,,,,,,,,,
Alabama,29927.9,28760.9,4728.0,14320.5,42.6,3291.8,0.0,5544.5,194.1,0.0,0.0,19.8,618.6,1.0
Alaska,3038.5,2772.4,168.9,1273.1,740.8,475.6,0.0,0.0,0.0,59.8,0.0,2.0,7.0,45.2
Arizona,31011.4,27579.7,2943.0,14156.2,90.5,2720.9,216.3,3937.0,2798.6,617.3,0.0,0.0,27.9,72.0
Arkansas,16472.7,14838.3,5128.1,6123.9,9.0,1265.8,30.0,1817.8,216.7,0.0,0.0,0.0,235.0,12.0
California,84731.9,79536.4,57.0,36974.5,420.1,10265.3,3911.9,2240.0,14410.1,6191.8,1849.9,331.8,1181.7,1701.3

In [79]:
state_agg.dtypes

Install_MW    float64
Total_MW      float64
Coal_MW       float64
NG_MW         float64
Crude_MW      float64
Hydro_MW      float64
HydroPS_MW    float64
Nuclear_MW    float64
Solar_MW      float64
Wind_MW       float64
Geo_MW        float64
Other_MW      float64
Bio_MW        float64
Bat_MW        float64
dtype: object

In [38]:
state_agg = state_agg.drop(['Install_MW', 'Other_MW'], axis=1)
state_agg

,Total_MW,Coal_MW,NG_MW,Crude_MW,Hydro_MW,HydroPS_MW,Nuclear_MW,Solar_MW,Wind_MW,Geo_MW,Bio_MW,Bat_MW
StateName,,,,,,,,,,,,
Alabama,28760.9,4728.0,14320.5,42.6,3291.8,0.0,5544.5,194.1,0.0,0.0,618.6,1.0
Alaska,2772.4,168.9,1273.1,740.8,475.6,0.0,0.0,0.0,59.8,0.0,7.0,45.2
Arizona,27579.7,2943.0,14156.2,90.5,2720.9,216.3,3937.0,2798.6,617.3,0.0,27.9,72.0
Arkansas,14838.3,5128.1,6123.9,9.0,1265.8,30.0,1817.8,216.7,0.0,0.0,235.0,12.0
California,79536.4,57.0,36974.5,420.1,10265.3,3911.9,2240.0,14410.1,6191.8,1849.9,1181.7,1701.3
Colorado,17845.1,4206.0,6560.5,150.5,691.0,580.8,0.0,790.5,4814.8,0.0,28.7,10.2
Connecticut,10009.2,0.0,5456.5,1962.3,119.4,29.4,2073.1,166.0,1.0,0.0,199.9,1.6
Delaware,3272.6,410.0,2559.3,114.1,0.0,0.0,0.0,38.0,2.0,0.0,14.2,0.0
District of Columbia,48.1,0.0,20.6,0.0,0.0,0.0,0.0,15.5,0.0,0.0,12.0,0.0
Florida,62372.7,6293.0,44512.5,1686.6,43.5,0.0,3666.0,4668.6,0.0,0.0,1160.6,29.0
Georgia,37407.9,8416.0,16638.6,1029.8,1985.0,1897.4,4061.0,2324.7,0.0,0.0,1053.2,2.2
Hawaii,3007.5,180.0,0.0,1979.9,32.4,0.0,0.0,283.5,233.2,43.0,153.9,75.0
Idaho,5215.0,5.0,1111.4,5.4,2769.7,0.0,0.0,242.0,970.4,10.0,86.3,0.0
Illinois,44597.1,9652.0,15761.6,664.6,32.9,0.0,11582.4,275.6,6300.6,0.0,80.2,132.7
Indiana,27175.7,14739.4,7928.8,98.3,69.1,0.0,0.0,382.2,3140.4,0.0,72.2,38.0
Iowa,21692.0,5284.0,3643.4,840.1,205.4,0.0,0.0,118.0,11576.6,0.0,20.6,3.9
Kansas,17482.8,4521.6,3818.8,552.0,7.0,0.0,1225.0,30.2,7318.4,0.0,9.0,0.0
Kentucky,17599.0,9403.0,6948.6,11.9,1134.9,0.0,0.0,26.1,0.0,0.0,74.5,0.0
Louisiana,25589.7,2774.5,18368.9,855.7,192.0,0.0,2132.9,74.5,0.0,0.0,422.1,0.5
Maine,4915.2,0.0,1607.3,844.7,725.8,0.0,0.0,106.3,994.2,0.0,568.6,46.3
Maryland,13166.7,2963.0,5990.7,1170.5,590.0,0.0,1725.8,384.8,190.0,0.0,140.9,5.0
Massachusetts,12616.1,0.0,7191.3,1829.4,266.3,1768.0,0.0,1056.7,105.7,0.0,284.2,114.5
Michigan,29823.6,7993.3,10567.4,505.3,264.4,2238.0,4086.5,241.9,3167.8,0.0,508.0,1.0
Minnesota,18264.6,4009.1,5457.4,784.8,214.5,0.0,1657.0,1076.5,4708.3,0.0,324.3,16.0
Mississippi,14603.2,1444.0,11227.3,9.0,0.0,0.0,1401.0,218.1,0.0,0.0,302.4,0.0
Missouri,22256.8,10488.0,5911.6,1094.6,548.5,657.0,1247.0,66.0,2227.8,0.0,14.1,2.2
Montana,5823.1,1630.5,388.0,52.0,2816.6,0.0,0.0,17.0,872.9,0.0,4.6,0.0
Nebraska,9984.2,3867.0,1959.2,351.5,279.7,0.0,770.0,29.1,2710.8,0.0,15.5,1.4
Nevada,12603.5,740.4,7075.2,6.0,1051.7,0.0,0.0,2943.9,150.0,595.0,9.8,25.0
New Hampshire,4477.5,533.9,1642.5,94.0,504.0,0.0,1247.8,2.4,211.9,0.0,241.0,0.0
New Jersey,17387.1,463.0,11463.3,307.7,12.3,420.0,3456.7,977.1,7.6,0.0,197.1,42.1
New Mexico,9656.0,2387.0,3274.1,46.0,82.7,0.0,0.0,735.8,3113.9,8.6,5.4,1.8
New York,39290.9,445.0,22862.2,3462.5,4558.3,1407.1,3203.0,710.0,2110.1,0.0,459.3,53.4
North Carolina,35072.3,9677.7,11557.5,502.0,2009.0,86.0,5149.6,5342.4,208.0,0.0,465.0,21.1
North Dakota,9486.1,3948.8,613.9,63.2,510.0,0.0,0.0,0.0,4326.7,0.0,9.8,0.0
Ohio,28252.4,10011.5,13436.9,649.1,101.9,0.0,2134.0,465.5,1102.3,0.0,138.3,33.8
Oklahoma,29202.7,3246.0,14767.1,79.8,849.8,258.0,0.0,45.5,9870.3,0.0,76.2,10.0
Oregon,16885.0,0.0,3753.4,0.0,8317.0,0.0,0.0,714.5,3759.5,19.5,316.1,5.0
Pennsylvania,49641.7,8593.0,25797.4,1509.2,899.6,1552.0,9093.2,155.2,1460.0,0.0,447.8,28.4
Puerto Rico,5796.5,454.4,1345.6,3609.5,98.1,0.0,0.0,154.6,99.0,0.0,4.8,30.5
Rhode Island,2082.2,0.0,1773.0,7.1,2.7,0.0,0.0,186.5,72.8,0.0,40.1,0.0
South Carolina,24135.6,4769.0,6525.9,467.6,1312.9,2796.0,6594.2,1111.5,0.0,0.0,554.5,4.0
South Dakota,6275.3,474.0,1213.8,215.1,1598.0,0.0,0.0,1.0,2767.2,0.0,5.4,0.8
Tennessee,21397.4,5845.3,6353.8,43.2,2608.6,1616.3,4522.7,182.2,29.1,0.0,196.2,0.0
Texas,136128.9,18141.6,70690.6,106.6,706.1,0.0,4980.0,7086.3,33197.2,0.0,385.8,352.8
Utah,9442.0,4581.0,2684.5,27.8,259.6,0.0,0.0,1375.7,389.7,70.7,12.8,0.0
Vermont,828.5,0.0,0.0,130.6,331.3,0.0,0.0,123.7,150.2,0.0,81.8,10.9
Virginia,28318.7,2536.0,14492.1,760.9,866.0,3241.0,3568.0,1941.8,12.0,0.0,804.9,0.0
Washington,30668.9,670.0,3386.4,15.2,21344.6,314.0,1151.0,23.4,3374.9,0.0,384.4,5.0
West Virginia,14920.1,12568.0,1205.1,11.0,340.8,0.0,0.0,0.0,742.5,0.0,3.2,49.5
Wisconsin,16261.4,5279.7,7418.3,638.0,410.6,0.0,1197.1,235.1,724.4,0.0,349.6,0.0
Wyoming,9598.7,6069.0,604.2,5.8,307.1,0.0,0.0,92.0,2504.9,0.0,0.0,0.0

In [69]:
state_agg = state_agg.apply(lambda x: x/1000.0)

TypeError: unsupported operand type(s) for /: 'str' and 'float'

Add national row

In [39]:
natl = state_agg.sum()
natl['StateName'] = 'National'
natl

Total_MW      1136065.0
Coal_MW        212738.7
NG_MW          490414.7
Crude_MW        30653.9
Hydro_MW        80090.2
HydroPS_MW      23019.2
Nuclear_MW      95464.3
Solar_MW        54857.4
Wind_MW        126588.0
Geo_MW           2596.7
Bio_MW          12809.5
Bat_MW           2985.1
StateName      National
dtype: object

In [40]:
state_agg = state_agg.reset_index()

In [41]:
state_agg = state_agg.append(natl, ignore_index=True)
state_agg

,StateName,Total_MW,Coal_MW,NG_MW,Crude_MW,Hydro_MW,HydroPS_MW,Nuclear_MW,Solar_MW,Wind_MW,Geo_MW,Bio_MW,Bat_MW
0,Alabama,28760.9,4728.0,14320.5,42.6,3291.8,0.0,5544.5,194.1,0.0,0.0,618.6,1.0
1,Alaska,2772.4,168.9,1273.1,740.8,475.6,0.0,0.0,0.0,59.8,0.0,7.0,45.2
2,Arizona,27579.7,2943.0,14156.2,90.5,2720.9,216.3,3937.0,2798.6,617.3,0.0,27.9,72.0
3,Arkansas,14838.3,5128.1,6123.9,9.0,1265.8,30.0,1817.8,216.7,0.0,0.0,235.0,12.0
4,California,79536.4,57.0,36974.5,420.1,10265.3,3911.9,2240.0,14410.1,6191.8,1849.9,1181.7,1701.3
5,Colorado,17845.1,4206.0,6560.5,150.5,691.0,580.8,0.0,790.5,4814.8,0.0,28.7,10.2
6,Connecticut,10009.2,0.0,5456.5,1962.3,119.4,29.4,2073.1,166.0,1.0,0.0,199.9,1.6
7,Delaware,3272.6,410.0,2559.3,114.1,0.0,0.0,0.0,38.0,2.0,0.0,14.2,0.0
8,District of Columbia,48.1,0.0,20.6,0.0,0.0,0.0,0.0,15.5,0.0,0.0,12.0,0.0
9,Florida,62372.7,6293.0,44512.5,1686.6,43.5,0.0,3666.0,4668.6,0.0,0.0,1160.6,29.0
10,Georgia,37407.9,8416.0,16638.6,1029.8,1985.0,1897.4,4061.0,2324.7,0.0,0.0,1053.2,2.2
11,Hawaii,3007.5,180.0,0.0,1979.9,32.4,0.0,0.0,283.5,233.2,43.0,153.9,75.0
12,Idaho,5215.0,5.0,1111.4,5.4,2769.7,0.0,0.0,242.0,970.4,10.0,86.3,0.0
13,Illinois,44597.1,9652.0,15761.6,664.6,32.9,0.0,11582.4,275.6,6300.6,0.0,80.2,132.7
14,Indiana,27175.7,14739.4,7928.8,98.3,69.1,0.0,0.0,382.2,3140.4,0.0,72.2,38.0
15,Iowa,21692.0,5284.0,3643.4,840.1,205.4,0.0,0.0,118.0,11576.6,0.0,20.6,3.9
16,Kansas,17482.8,4521.6,3818.8,552.0,7.0,0.0,1225.0,30.2,7318.4,0.0,9.0,0.0
17,Kentucky,17599.0,9403.0,6948.6,11.9,1134.9,0.0,0.0,26.1,0.0,0.0,74.5,0.0
18,Louisiana,25589.7,2774.5,18368.9,855.7,192.0,0.0,2132.9,74.5,0.0,0.0,422.1,0.5
19,Maine,4915.2,0.0,1607.3,844.7,725.8,0.0,0.0,106.3,994.2,0.0,568.6,46.3
20,Maryland,13166.7,2963.0,5990.7,1170.5,590.0,0.0,1725.8,384.8,190.0,0.0,140.9,5.0
21,Massachusetts,12616.1,0.0,7191.3,1829.4,266.3,1768.0,0.0,1056.7,105.7,0.0,284.2,114.5
22,Michigan,29823.6,7993.3,10567.4,505.3,264.4,2238.0,4086.5,241.9,3167.8,0.0,508.0,1.0
23,Minnesota,18264.6,4009.1,5457.4,784.8,214.5,0.0,1657.0,1076.5,4708.3,0.0,324.3,16.0
24,Mississippi,14603.2,1444.0,11227.3,9.0,0.0,0.0,1401.0,218.1,0.0,0.0,302.4,0.0
25,Missouri,22256.8,10488.0,5911.6,1094.6,548.5,657.0,1247.0,66.0,2227.8,0.0,14.1,2.2
26,Montana,5823.1,1630.5,388.0,52.0,2816.6,0.0,0.0,17.0,872.9,0.0,4.6,0.0
27,Nebraska,9984.2,3867.0,1959.2,351.5,279.7,0.0,770.0,29.1,2710.8,0.0,15.5,1.4
28,Nevada,12603.5,740.4,7075.2,6.0,1051.7,0.0,0.0,2943.9,150.0,595.0,9.8,25.0
29,New Hampshire,4477.5,533.9,1642.5,94.0,504.0,0.0,1247.8,2.4,211.9,0.0,241.0,0.0
30,New Jersey,17387.1,463.0,11463.3,307.7,12.3,420.0,3456.7,977.1,7.6,0.0,197.1,42.1
31,New Mexico,9656.0,2387.0,3274.1,46.0,82.7,0.0,0.0,735.8,3113.9,8.6,5.4,1.8
32,New York,39290.9,445.0,22862.2,3462.5,4558.3,1407.1,3203.0,710.0,2110.1,0.0,459.3,53.4
33,North Carolina,35072.3,9677.7,11557.5,502.0,2009.0,86.0,5149.6,5342.4,208.0,0.0,465.0,21.1
34,North Dakota,9486.1,3948.8,613.9,63.2,510.0,0.0,0.0,0.0,4326.7,0.0,9.8,0.0
35,Ohio,28252.4,10011.5,13436.9,649.1,101.9,0.0,2134.0,465.5,1102.3,0.0,138.3,33.8
36,Oklahoma,29202.7,3246.0,14767.1,79.8,849.8,258.0,0.0,45.5,9870.3,0.0,76.2,10.0
37,Oregon,16885.0,0.0,3753.4,0.0,8317.0,0.0,0.0,714.5,3759.5,19.5,316.1,5.0
38,Pennsylvania,49641.7,8593.0,25797.4,1509.2,899.6,1552.0,9093.2,155.2,1460.0,0.0,447.8,28.4
39,Puerto Rico,5796.5,454.4,1345.6,3609.5,98.1,0.0,0.0,154.6,99.0,0.0,4.8,30.5
40,Rhode Island,2082.2,0.0,1773.0,7.1,2.7,0.0,0.0,186.5,72.8,0.0,40.1,0.0
41,South Carolina,24135.6,4769.0,6525.9,467.6,1312.9,2796.0,6594.2,1111.5,0.0,0.0,554.5,4.0
42,South Dakota,6275.3,474.0,1213.8,215.1,1598.0,0.0,0.0,1.0,2767.2,0.0,5.4,0.8
43,Tennessee,21397.4,5845.3,6353.8,43.2,2608.6,1616.3,4522.7,182.2,29.1,0.0,196.2,0.0
44,Texas,136128.9,18141.6,70690.6,106.6,706.1,0.0,4980.0,7086.3,33197.2,0.0,385.8,352.8
45,Utah,9442.0,4581.0,2684.5,27.8,259.6,0.0,0.0,1375.7,389.7,70.7,12.8,0.0
46,Vermont,828.5,0.0,0.0,130.6,331.3,0.0,0.0,123.7,150.2,0.0,81.8,10.9
47,Virginia,28318.7,2536.0,14492.1,760.9,866.0,3241.0,3568.0,1941.8,12.0,0.0,804.9,0.0
48,Washington,30668.9,670.0,3386.4,15.2,21344.6,314.0,1151.0,23.4,3374.9,0.0,384.4,5.0
49,West Virginia,14920.1,12568.0,1205.1,11.0,340.8,0.0,0.0,0.0,742.5,0.0,3.2,49.5
50,Wisconsin,16261.4,5279.7,7418.3,638.0,410.6,0.0,1197.1,235.1,724.4,0.0,349.6,0.0
51,Wyoming,9598.7,6069.0,604.2,5.8,307.1,0.0,0.0,92.0,2504.9,0.0,0.0,0.0
52,National,1136065.0,212738.7,490414.7,30653.9,80090.2,23019.2,95464.3,54857.4,126588.0,2596.7,12809.5,2985.1

TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [42]:
df.to_csv('Power_Plants_state_and_natl_agg.csv')